"""Added subscriptions tables

Revision ID: 06a2aea441e0
Revises: 3a828a90bf0e
Create Date: 2021-10-25 20:54:12.168118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a2aea441e0'
down_revision = '3a828a90bf0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribe_plan_id', sa.Integer(), server_default='1', nullable=True))
    op.create_foreign_key(None, 'user', 'subscribeplan', ['subscribe_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'subscribe_plan_id')
    # ### end Alembic commands ###
